# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[37,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/Machines/issues"
logoFile="machines.png"
license="LGPL 3"

[[mods]]
modId="simple_machines"
version="${file.jarVersion}"
displayName="SimpleOres:Machines"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/Machines/1.17/update.json"
displayURL="http://minecraft.curseforge.com/projects/machines"
credits="Created by AleXndrTheGr8st, updated and maintained by Sinhika"
authors="AleXndrTheGr8st, Sinhika"
description='''An addon for SimpleOres that adds improved furnaces, blast furnaces, and smokers. The Mythril series cooks faster (and thus burns less fuel), while the Onyx series has a chance of yielding extra outputs.
        
Additional Credits:  mindy15963 (Korean translations), vanja-san (Russian), burunduk (Ukrainian) Unknown, but probably fearheaven (French).
'''

[[dependencies.simple_machines]] #optional
    modId="forge"
    mandatory=true
    versionRange="[37.0.31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simple_machines]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simple_machines]]
    modId="simplecorelib"
    mandatory=true
    versionRange="[1.17.1-3.0.0.5,1.17.1-3.1.0.0)"
    ordering="NONE"
    side="BOTH"
        
[[dependencies.simple_machines]]
    modId="simpleores"
    mandatory=true
    versionRange="[1.17.1-3.0.0.1,1.17.1-3.1.0.0)"
    ordering="NONE"
    side="BOTH"
        
# [[dependencies.simple_machines]] #optional
#     modId="jei"
#     mandatory=false
#     versionRange="[1.16.4-7.6.1.65,)"
#     ordering="BEFORE"
#     side="BOTH"
    
