# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}" #mandatory
issueTrackerURL="https://github.com/Sinhika/Machines/issues"
logoFile="machines.png"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/Machines/1.19/update.json"
displayURL="http://minecraft.curseforge.com/projects/machines"
credits="Created by AleXndrTheGr8st, updated and maintained by Sinhika"
authors="${mod_authors}"
description='''An addon for SimpleOres that adds improved furnaces, blast furnaces, and smokers. The Mythril series cooks faster (and thus burns less fuel), while the Onyx series has a chance of yielding extra outputs.
        
Additional Credits:  mindy15963 (Korean translations), vanja-san (Russian), burunduk (Ukrainian) Unknown, but probably fearheaven (French).
'''

[[dependencies.${mod_id}]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="simplecorelib"
    mandatory=true
    versionRange="${simplecore_range}"
    ordering="NONE"
    side="BOTH"
        
[[dependencies.${mod_id}]]
    modId="simpleores"
    mandatory=true
    versionRange="${simpleores_range}"
    ordering="NONE"
    side="BOTH"
